# Generated by Django 4.1.6 on 2024-07-07 20:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_number', models.CharField(default='', max_length=20, unique=True)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('address', models.TextField(default='')),
                ('phone_number', models.CharField(default='', max_length=15)),
                ('loan_amount', models.IntegerField(default=5000)),
                ('per_day_emi', models.IntegerField(default=100)),
                ('opening_date', models.DateField(default=datetime.date.today)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.IntegerField(blank=True, null=True)),
                ('emi_due', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('received_amount', models.IntegerField(default=0)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='customer_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('empid', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emi_date', models.DateField()),
                ('per_day_emi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('picked_by', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateField(default=datetime.date.today)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeapp.customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeapp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='CashEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount_received', models.IntegerField()),
                ('customer_number', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='financeapp.customer')),
                ('picked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeapp.employee')),
            ],
        ),
    ]
