# Generated by Django 4.1.6 on 2024-07-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='guarantor_name',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='guarantor_phone_number',
            field=models.CharField(blank=True, default='NA', max_length=15),
        ),
    ]
