# Generated by Django 4.1.6 on 2024-07-08 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0002_customer_guarantor_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField()),
                ('date', models.DateField()),
                ('opening_outstand', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dea', models.DecimalField(decimal_places=2, max_digits=10)),
                ('closing_outstand', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status_paid_unpaid', models.CharField(blank=True, max_length=10, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeapp.customer')),
            ],
        ),
    ]
