# Generated by Django 4.1.6 on 2024-07-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0003_loandetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandetail',
            name='outstanding_amount',
            field=models.IntegerField(default=0),
        ),
    ]
