# Generated by Django 4.1.6 on 2024-07-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0004_loandetail_outstanding_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandetail',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loandetail',
            name='outstanding_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
