# Generated by Django 4.1.6 on 2024-07-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0007_loandetail_daily_collection_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandetail',
            name='daily_collection_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
