# Generated by Django 4.1.6 on 2024-07-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0009_alter_loandetail_daily_collection_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandetail',
            name='daily_collection_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
