# Generated by Django 4.1.6 on 2024-07-09 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0010_alter_loandetail_daily_collection_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CashEntry',
        ),
    ]
