# Generated by Django 4.1.6 on 2024-07-09 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0011_delete_cashentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='opening_date',
            field=models.DateField(default=datetime.date(2024, 7, 10)),
        ),
    ]
