# Generated by Django 4.1.6 on 2024-07-09 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0015_employee_cash_picked_date_employee_total_cash_picked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('daily_collection', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('loan_distribution', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('add_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
