# Generated by Django 4.1.6 on 2024-07-10 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0016_dailytransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loandetail',
            name='outstanding_amount',
        ),
    ]
